Added some functions for maintaining an ssh-agent session

diff --git a/files/zshrc.d/functions b/files/zshrc.d/functions
--- a/files/zshrc.d/functions
+++ b/files/zshrc.d/functions
@@ -61,3 +61,39 @@ dotheargo () {
     echo
     echo "Argo Hostname: ${ARGO_HOSTNAME}"
 }
+
+killagent () {
+    ssh-agent -k
+    unset SSH_AUTH_SOCK
+    unset SSH_AGENT_PID
+    rm ~/.ssh-agent
+}
+
+newagent () {
+    if [[ -e ~/.ssh-agent ]]; then
+        killagent
+    fi
+
+    ssh-agent -s > ~/.ssh-agent
+    eval $(cat ~/.ssh-agent)
+    ssh-add ~/.ssh/id_rsa
+}
+
+loadagent () {
+    # If the agent pid env var isn't set, try to load the agent
+    if [[ -z "${SSH_AGENT_PID}" ]]; then
+        if [[ -e ~/.ssh-agent ]]; then
+            eval $(cat ~/.ssh-agent)
+        fi
+    fi
+
+    # If this fails, an agent couldn't be loaded
+    if ! ( ssh-add -l ); then
+        newagent
+    fi
+}
+
+g () {
+    loadagent
+    eval $(brew --prefix git)/bin/git $@
+}
